#!/usr/bin/env bash

FUZZ_TARGETS_LIST="curl_fuzzer_dict curl_fuzzer_file curl_fuzzer_ftp curl_fuzzer_gopher curl_fuzzer_http curl_fuzzer_https curl_fuzzer_imap curl_fuzzer_ldap curl_fuzzer_mqtt curl_fuzzer_pop3 curl_fuzzer_rtsp curl_fuzzer_smb curl_fuzzer_smtp curl_fuzzer_tftp curl_fuzzer_ws curl_fuzzer fuzz_url fuzz_bufq fuzz_doh fuzz_altsvc fuzz_cookie fuzz_escape fuzz_hsts fuzz_mime fuzz_netrc fuzz_parsedate fuzz_setopt fuzz_url_extended"

# The structured fuzzer is 64-bit only.
if [ "${ARCHITECTURE:-}" != "i386" ]; then
    FUZZ_TARGETS_LIST="${FUZZ_TARGETS_LIST} curl_fuzzer_proto"
fi

export FUZZ_TARGETS="${FUZZ_TARGETS_LIST}"
